### ISSUE TITLE
Make pools in the Top 5 category clickable

### ISSUE THREAD

**Issue by shanzzam** [stellar/amm-reference-ui#46]
### What problem does your feature solve?
The LPs listed in the Top 5 Pools are most likely ones users want to explore. However we don't provide a way to organize the pools by # of trustlines. I'd like an easier way to explore an LP in a detailed web page with out having to hunt through the full list of pools.

### What would you like to see?
Make the pool name pairs clickable, similar to how they can be clicked in the larger list and a detailed page for that pool is displayed. For example, clicking on XML/USDC below would take me to [that LP page](https://amm-demo.stellar.org/pool/bb4e56ed4d47d4ee09c772021b60d2698fe6567e4148f976ffc0af23b5e66e4a)

![top_pools_interactive](https://user-images.githubusercontent.com/5062622/144328886-ada9b21a-0c47-477c-836c-2809ca2d98a2.png)

**Comment by piyalbasu** [comment]
Completed as part of Release v1.0.1
